version: '3.7'
services:
  mongo:
    image: "mongo:3.6"
    container_name: mongo2-lib
    restart: always
    networks:
      - mongo2-lib-network

  test:
    build: 
      context: .
      target: test
    image: "mongo2-lib:test"
    networks:
      - mongo2-lib-network
    depends_on:
      - mongo
    environment:
      - LOG_LEVEL=error
      - MONGO_URL=mongo2-lib:27017
      - WAIT_HOSTS=mongo2-lib:27017

networks:
  mongo2-lib-network:
    driver: bridge
